# Generated by Django 5.0.14 on 2026-07-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_exchangerequest_meeting_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerequest',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exchangerequest',
            name='meeting_platform',
            field=models.CharField(blank=True, choices=[('google_meet', 'Google Meet'), ('teams', 'Microsoft Teams')], max_length=50, null=True),
        ),
    ]
